#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : php-protobuf
Version  : 3.9.2
Release  : 3
URL      : https://pecl.php.net/get/protobuf-3.9.2.tgz
Source0  : https://pecl.php.net/get/protobuf-3.9.2.tgz
Summary  : Google's language-neutral, platform-neutral, extensible mechanism for serializing structured data.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: php-protobuf-lib = %{version}-%{release}
BuildRequires : buildreq-php

%description
No detailed description available

%package lib
Summary: lib components for the php-protobuf package.
Group: Libraries

%description lib
lib components for the php-protobuf package.


%prep
%setup -q -n protobuf-3.9.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
phpize
%configure
make  %{?_smp_mflags}

%install
%make_install


%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/extensions/no-debug-non-zts-20180731/protobuf.so
